runtime: python312  # Choose the appropriate Python version
entrypoint: gunicorn -b :$PORT app:app  # Entry point to your app

env_variables:
  FLASK_APP: app.py
  FLASK_DEBUG: 'False'
  VERSION: '1.0.0'
  ENV: 'production'

instance_class: F2  

handlers:
  - url: /static
    static_dir: static/
  - url: /.*  # This will route all other URLs to your Flask app
    script: auto

automatic_scaling:
  min_instances: 1  # Keeps at least one instance running
  max_instances: 2  # You can adjust the max limit as needed
  target_cpu_utilization: 0.65  # Target CPU utilization for scaling