fake_feedback_data = [
        {'feedback': 0, 'probabilities': {'spectral': 0.12, 'blurring': 0.24}},
        {'feedback': 1, 'probabilities': {'spectral': 0.65, 'blurring': 0.79}},
        {'feedback': 0, 'probabilities': {'spectral': 0.3, 'blurring': 0.1}},
        {'feedback': 1, 'probabilities': {'spectral': 0.55, 'blurring': 0.88}},
        {'feedback': 0, 'probabilities': {'spectral': 0.2, 'blurring': 0.35}},
        {'feedback': 1, 'probabilities': {'spectral': 0.72, 'blurring': 0.7}},
        {'feedback': 0, 'probabilities': {'spectral': 0.1, 'blurring': 0.15}},
        {'feedback': 1, 'probabilities': {'spectral': 0.85, 'blurring': 0.9}},
        {'feedback': 0, 'probabilities': {'spectral': 0.25, 'blurring': 0.45}},
        {'feedback': 1, 'probabilities': {'spectral': 0.68, 'blurring': 0.78}},
        {'feedback': 0, 'probabilities': {'spectral': 0.4, 'blurring': 0.2}},
        {'feedback': 1, 'probabilities': {'spectral': 0.75, 'blurring': 0.85}},
        {'feedback': 0, 'probabilities': {'spectral': 0.18, 'blurring': 0.28}},
        {'feedback': 1, 'probabilities': {'spectral': 0.62, 'blurring': 0.74}},
        {'feedback': 0, 'probabilities': {'spectral': 0.3, 'blurring': 0.5}},
        {'feedback': 1, 'probabilities': {'spectral': 0.77, 'blurring': 0.82}},
        {'feedback': 0, 'probabilities': {'spectral': 0.2, 'blurring': 0.33}},
        {'feedback': 1, 'probabilities': {'spectral': 0.64, 'blurring': 0.77}},
        {'feedback': 0, 'probabilities': {'spectral': 0.15, 'blurring': 0.22}},
        {'feedback': 1, 'probabilities': {'spectral': 0.9, 'blurring': 0.91}},
        {'feedback': 0, 'probabilities': {'spectral': 0.05, 'blurring': 0.08}},
        {'feedback': 1, 'probabilities': {'spectral': 0.77, 'blurring': 0.93}},
        {'feedback': 0, 'probabilities': {'spectral': 0.2, 'blurring': 0.29}},
        {'feedback': 1, 'probabilities': {'spectral': 0.82, 'blurring': 0.87}},
        {'feedback': 0, 'probabilities': {'spectral': 0.35, 'blurring': 0.42}},
        {'feedback': 1, 'probabilities': {'spectral': 0.58, 'blurring': 0.77}},
        {'feedback': 0, 'probabilities': {'spectral': 0.3, 'blurring': 0.18}},
        {'feedback': 1, 'probabilities': {'spectral': 0.65, 'blurring': 0.81}},
        {'feedback': 0, 'probabilities': {'spectral': 0.14, 'blurring': 0.25}},
        {'feedback': 1, 'probabilities': {'spectral': 0.58, 'blurring': 0.72}},
        {'feedback': 0, 'probabilities': {'spectral': 0.28, 'blurring': 0.37}},
        {'feedback': 1, 'probabilities': {'spectral': 0.73, 'blurring': 0.88}},
        {'feedback': 0, 'probabilities': {'spectral': 0.25, 'blurring': 0.3}},
        {'feedback': 1, 'probabilities': {'spectral': 0.67, 'blurring': 0.79}},
        {'feedback': 0, 'probabilities': {'spectral': 0.2, 'blurring': 0.4}},
        {'feedback': 1, 'probabilities': {'spectral': 0.79, 'blurring': 0.85}},
        {'feedback': 0, 'probabilities': {'spectral': 0.12, 'blurring': 0.2}},
    ]
fake_metamodel_data = {'features':['spectral','blurring','intercept'], 
            'param_values': [0.12345,0.22121,0.2556556], 
            'accuracy':0.123456, 
            'f1_score': 0.65432,
            'checkpoint_time':'2025-02-22',}
fake_probabilities_data = {'blurring': 0.334121, 'spectral':0.112341}